// All 30 Sim ladder projects. Edit this list to add/change projects.
// archetypeKey drives the pill colour. tier drives the difficulty band.
const PROJECTS = [
  {n:1,tier:"Warm-up",archetypeKey:"build",archetype:"Build-type · greenfield",sector:"Retail",title:"Loyalty points service for a coffee chain",
   summary:"A clean standalone API that tracks loyalty points — earn, redeem, check balance — pulled out of the POS app so any consumer can reuse it.",
   stack:["C#",".NET 8","Clean Architecture","EF Core","SQL Server","xUnit","Swagger"],
   brief:"Snapple Coffee (a 400-store chain) wants a small, clean API that tracks loyalty points: earn on purchase, redeem at checkout, check balance. Their current logic is buried inside the POS app and nobody can reuse it. Build it as a standalone service the POS and the future mobile app can both call. Keep it boringly correct — this is about clean fundamentals, not cleverness.",
   builds:["A minimal .NET 8 Web API with endpoints for earn, redeem, and balance.","Clean architecture: separate domain (points rules), application (use cases), infrastructure (storage).","SQL Server (or SQLite for the demo) with EF Core; a ledger table so balance is always derivable, never just stored.","Swagger/OpenAPI docs so any consumer can self-serve.","xUnit tests covering earn, redeem, and the can't-redeem-more-than-you-have rule."],
   effort:"S — about 2–3 person-days. One mid-level dev could do it; he should do it fast and set the code-quality bar for the rest of the ladder.",
   cost:"Near-zero infra (free-tier DB, runs locally or free host). One developer, no DevOps. This is the cost baseline everything else is measured against.",
   accept:["Repo with a README explaining the domain in plain English and how to run it.","Swagger page loads and every endpoint works from it.","Balance is always computed from the ledger, never trusted as a stored figure.","Tests pass and cover the overspend rule.","Deployed demo link OR a short Loom/GIF of Swagger in action."],
   questions:["Why a ledger instead of a single balance column? What does that buy you and what does it cost?","How would this behave if two redemptions hit the same account at the same second?","If we put this in front of 400 stores tomorrow, what breaks first?"],
   stretch:"Add an idempotency key on earn/redeem so a retried POS request can't double-count."},

  {n:2,tier:"Warm-up",archetypeKey:"build",archetype:"Build-type · integration",sector:"Logistics / Shipping",title:"Container status webhook normaliser",
   summary:"Ingest container status from three carriers in three different formats, normalise to one clean event shape, and expose a single feed plus a \"where is container X\" lookup.",
   stack:["C#",".NET 8","Adapter pattern","System.Text.Json","System.Xml","CsvHelper","Serilog","xUnit"],
   brief:"Woogle Freight receives shipping-container status updates from three carriers, each in a different format (one JSON, one XML, one a flat CSV drop). Ops staff currently eyeball three dashboards. Build a small service that ingests all three, normalises them into one consistent event shape, and exposes a single clean feed plus a \"where is container X\" lookup. Mirrors the Partner Integration API pattern — many messy inbound formats, one clean internal contract — in a shipping context.",
   builds:["Ingestion endpoints/handlers for three differently-shaped inputs (JSON, XML, CSV).","A single normalised internal event model; an adapter per carrier.","A query endpoint: latest known status for a given container number.","Structured logging so a failed mapping is visible, not silent.","Tests proving all three formats land as the same normalised shape."],
   effort:"S–M — about 3–4 person-days. The mapping is the real work; the API around it is light.",
   cost:"Low; runs on a single small instance. One backend dev. The reusable value is the normalisation layer — call that out as the asset.",
   accept:["All three sample formats ingest and produce identical normalised events.","Lookup returns the most recent status for a container.","A deliberately malformed input is logged and rejected cleanly, not crashed on.","README shows the three input samples and the one output shape side by side.","Repo + demo (Swagger or a tiny status page)."],
   questions:["A fourth carrier joins next quarter — how much of your code changes? (Good answer: only a new adapter.)","How do you handle a status update that arrives out of order, older than what you already have?","Where would this fall over at 10,000 containers an hour, and what's the cheapest fix?"],
   stretch:"Add config-driven mapping so a new carrier is onboarded by configuration rather than new code — the lever from the Partner Integration API."},

  {n:3,tier:"Core",archetypeKey:"build",archetype:"Build-type · document workflow",sector:"Pharma / Healthcare",title:"Clinical document vault with controlled access",
   summary:"A service managing trial documents — upload, role-based controlled access, retrieval by study ID — with a tamper-evident audit trail for a regulated environment.",
   stack:["C#",".NET 8","Azure Blob / MinIO","Azure Key Vault","JWT/claims auth","SQL Server","Swagger","xUnit"],
   brief:"Medex Labs needs a service to manage trial documents — upload, controlled access by role, and retrieval by study ID. Regulated environment: every access must be auditable, and documents must never be served to someone without the right role. This is the Document Storage & Access and DigiLocker work re-pointed at pharma compliance.",
   builds:["A .NET API over blob storage (Azure Blob, or local/MinIO for the demo) for upload and retrieval.","Role-based access (investigator, monitor, auditor) — each sees only what their role allows.","An immutable, append-only audit log: who accessed what, when.","Retrieval organised by study/subject ID, mirroring the policy-number retrieval pattern.","Secrets pulled from config/Key Vault, never hard-coded."],
   effort:"M — about 5–6 person-days. Access control and the audit trail are where the time goes, not the upload.",
   cost:"Moderate: blob storage + a DB. One senior dev; half-day security review. In a real pharma setting you'd also budget for compliance sign-off — worth naming even if he can't do it himself.",
   accept:["A user without the right role is denied and the denial is logged.","Every successful access writes an immutable audit entry.","Documents retrievable by study ID; no way to enumerate other studies' docs.","No secret values anywhere in the repo.","README explains the roles and the compliance reasoning. Repo + demo."],
   questions:["How do you guarantee the audit log can't be tampered with after the fact?","If a regulator asks \"prove document X was only ever seen by authorised people,\" can your system answer that in one query?","What's your effort estimate to add a new role, and why should it be small?"],
   stretch:"Add time-boxed access (a grant that expires), echoing the DigiLocker retrieval flow."},

  {n:4,tier:"Core",archetypeKey:"polish",archetype:"Snapple-type · polish",sector:"Pure tech play",title:"Public developer API that feels world-class",
   summary:"A simple-on-purpose public API (URL shortener or currency conversion) built to a developer-experience team's standard: flawless docs, consistent errors, rate limits, versioning. The test is craft, not features.",
   stack:["C#",".NET 8","Minimal APIs","API versioning","ProblemDetails","rate limiting","OpenAPI","Serilog"],
   brief:"Snapple Computers is releasing a public API and cares more about how it feels to developers than about raw features — their whole brand is polish. Take a simple domain (a URL-shortener or currency-conversion service) and build the API a demanding developer-experience team would ship: flawless docs, consistent errors, sensible rate limits, versioning. The functionality is easy on purpose; the bar is craft.",
   builds:["A small but complete .NET API with a clean, versioned contract (v1).","Consistent, documented error format across every endpoint (RFC-style problem details).","Rate limiting and clear 429 behaviour.","First-class OpenAPI docs and a genuinely good README — a stranger integrates in 10 minutes.","Health check endpoint and structured logs."],
   effort:"M — about 4–5 person-days. The features are quick; the polish (errors, docs, edge cases) is the real spend and the whole point.",
   cost:"Low infra. One senior dev who cares about craft. The \"cost\" here is attention, not money — a good talking point about why polish work is under-resourced.",
   accept:["Every error, anywhere, comes back in the same documented shape.","Hitting the rate limit returns a clean, explained 429.","A new developer can read the README and make a successful call without asking a question.","Versioning is in place so a v2 wouldn't break v1 users.","Repo + live demo + the OpenAPI page."],
   questions:["What does \"good developer experience\" actually mean, and how would you measure it?","Why version from day one when there's only one consumer?","Where's the line between polish that matters and gold-plating that wastes effort?"],
   stretch:"Publish a small client SDK (a NuGet-style package) so consumers don't hand-roll HTTP calls."},

  {n:5,tier:"Core",archetypeKey:"debug",archetype:"Debug-type · inherited code",sector:"Fintech",title:"Find and fix the bug a junior shipped",
   summary:"A junior's transaction-fee calculator is subtly wrong on a fraction of transactions. Handed the code cold: find it, prove it, fix it minimally, don't break the working cases. (Broken codebase provided separately.)",
   stack:["C#",".NET 8","xUnit","debugging","decimal vs double","Git"],
   brief:"A junior developer on a fintech payments team shipped a transaction-fee calculation service. It mostly works — but finance reports that a small fraction of transactions are charged the wrong fee, and occasionally a refund comes out positive when it should be negative. You're handed the codebase cold: find it, fix it, prove it's fixed, don't break the working cases. The realistic first-week-on-a-new-team task. A broken codebase is provided separately so he's genuinely debugging, not building.",
   builds:["Read and understand an unfamiliar .NET codebase with a planted, subtle bug (rounding / sign / boundary).","Reproduce the failure with a failing test before touching the fix.","Fix it with the smallest correct change; resist rewriting what isn't broken.","Add regression tests so it can never silently come back.","Write a short root-cause note: what was wrong, why it slipped through, how to prevent the class of bug."],
   effort:"S–M — about 2–4 person-days, but unpredictable: debugging is non-linear. Honest estimate: \"a day to find it, a day to prove and fix, a day if it hides.\"",
   cost:"Almost no infra — pure engineering time. One developer. The point: he can be dropped into someone else's mess and create order, which is most of senior work.",
   accept:["A test that fails on the original code and passes after the fix.","The working transactions still behave correctly (no regressions).","The fix is minimal and explained.","A written root-cause analysis in the README.","Repo with the before/after visible in commit history."],
   questions:["How did you isolate it without rewriting everything?","Why decimal and not double for money — and how does that connect to this bug?","How would you stop this entire category of bug across the codebase, not just this instance?"],
   stretch:"A second, harder bug (a concurrency/race issue) can be planted once the first is solved, to raise difficulty live."},

  {n:6,tier:"Hard",archetypeKey:"rescue",archetype:"Rescue-type · turnaround",sector:"Sustainability / Energy",title:"Six-month-stalled carbon reporting platform, shipped lean",
   summary:"A carbon-reporting platform stuck for six months with ballooned scope and a tight budget. Come in, cut scope ruthlessly, and ship something real and usable on minimum spend.",
   stack:["C#",".NET 8","Blazor","EF Core","QuestPDF","Azure App Service","GitHub Actions"],
   brief:"GreenLedger has been trying to build a carbon-emissions reporting platform for six months. Scope ballooned, nothing shipped, the board is impatient, the budget is now tight. You're brought in to rescue it: deliver something real and usable in a short window, on minimum spend, by ruthlessly cutting scope to the core that matters — ingest emissions data, compute a footprint, produce a credible report.",
   builds:["Define the smallest version that delivers real value; write a one-page scope-cut memo (what you cut and why).","Ingest emissions data (CSV/API) for a few sources; compute totals against simple, documented factors.","Generate a clean report (PDF or web) a non-technical stakeholder can actually use.","Ship it deployed and working, not a prototype on localhost.","Be explicit about what's deliberately deferred to \"phase 2\"."],
   effort:"M–L — about 6–8 person-days of build, but the headline skill is scope-cutting, not coding. The estimate itself is the deliverable: \"here's what I ship in two weeks and what I won't.\"",
   cost:"Deliberately low: cheapest viable hosting, one developer, no expansion until value is proven. Maximum output per unit spend.",
   accept:["A written scope-cut memo: what shipped, what was dropped, why.","Data ingests and a real report comes out the other end.","It's deployed and a stranger can use it.","The deferred work is named, so stakeholders trust the plan.","Repo + live demo + the memo."],
   questions:["What did you cut, and how did you decide core vs nice-to-have?","How do you defend shipping something \"incomplete\" to an impatient board?","If you got one more developer for two weeks, exactly what would you spend them on — and what would you still refuse to build yet?"],
   stretch:"Add per-source data quality flags so the report shows confidence, not just numbers."},

  {n:7,tier:"Hard",archetypeKey:"ai",archetype:"AI-agent-type · build",sector:"Media / Broadcasting",title:"Newsroom transcript-to-insight agent",
   summary:"An AI agent that ingests transcripts and does editorial work — summarise, pull quotes, tag topics, flag fact-checks, draft a social post — and escalates ambiguous calls to a human. The hard part is reliability, not the LLM call.",
   stack:["C#",".NET 8","OpenAI API / Ollama","structured output","JSON schema validation","background processing","Serilog","xUnit"],
   brief:"Woogle News wants an AI agent that ingests interview and broadcast transcripts and does real editorial work: summarise, pull quotable lines, tag topics, flag anything needing fact-checking, and draft a short social post — then escalate genuinely ambiguous calls to a human. Plays to his media background and emerging GenAI track. The hard part is making an agent reliable and bounded, not just calling an LLM.",
   builds:["A .NET service that takes a transcript and runs a multi-step agent pipeline (summarise → extract → tag → draft).","Integrate an LLM (OpenAI API, or Ollama locally to keep cost at zero).","Structured, validated output (JSON schema) — not free text the downstream can't trust.","A confidence/escalation rule: low-confidence items get flagged for a human, not auto-published.","Guardrails: handle the model returning garbage without crashing the pipeline."],
   effort:"L — about 8–10 person-days. The LLM call is easy; reliability, validation, and escalation logic are where senior judgement shows.",
   cost:"Variable cost, and that's a feature to discuss: OpenAI scales per token, Ollama is free but needs a machine. Reasoning about that trade-off is the point. One developer with AI fluency.",
   accept:["Given a transcript, the agent returns valid structured output every time, or fails loudly — never silently wrong.","Low-confidence outputs are escalated, not published.","A deliberately weird transcript doesn't crash it.","README explains the pipeline, the escalation rule, and the cost model (OpenAI vs Ollama).","Repo + demo (even a CLI or simple page that takes a transcript and shows output)."],
   questions:["How do you stop an LLM-based feature from confidently making things up?","What's your cost model at 10,000 transcripts a month, and how would you cut it?","Where exactly is the line between what the agent decides and what a human must?"],
   stretch:"Add an eval harness — test transcripts with expected tags — so quality is measured, not vibes."},

  {n:8,tier:"Brutal",archetypeKey:"architect",archetype:"Architect-type · consolidation",sector:"Retail (enterprise)",title:"Consolidate a retailer's tangled inventory APIs",
   summary:"Eleven contradicting inventory services built over a decade. Design and prove a consolidation into one observable source of truth with per-consumer tracking. His CSAPI Clover-Champion win, replayed at enterprise retail scale.",
   stack:["C#",".NET 8","Vertical Slice","CQRS / MediatR","Azure API Management","OpenTelemetry","SQL Server","ADRs","C4 diagrams"],
   brief:"MegaMart has eleven internal services that all touch inventory, built by different teams over a decade. They contradict each other, nobody trusts the numbers, and a single \"how much stock do we have\" question takes three teams to answer. You're the architect brought in to design and prove a consolidation — one observable source of truth with per-consumer tracking. Literally his CSAPI win, replayed at enterprise retail scale; he documents and demonstrates it as a portable architecture.",
   builds:["An architecture decision record (ADR) and a clear diagram — current mess vs target state.","A working reference implementation of the unified inventory API (model 2–3 sources realistically, not all 11).","Per-consumer usage tracking, so you know who calls what (his CSAPI signature feature).","A migration strategy: how legacy consumers move over without a big-bang cutover.","Observability: metrics/logging so the single source of truth is actually trustworthy."],
   effort:"L — the real thing is months; the portfolio version is ~8–10 person-days for the ADR, diagrams, and a convincing reference slice. The deliverable is the thinking as much as the code.",
   cost:"Enterprise context: realistically a small team over a quarter, plus API Management licensing. Present it as a phased programme with a cost curve, not a single number — architect-level framing.",
   accept:["An ADR a real architecture panel would accept.","A reference API that unifies 2–3 modelled sources into one contract.","Per-consumer usage is tracked and queryable.","A written, phased migration plan (no big-bang).","Repo + diagrams + demo of the unified endpoint."],
   questions:["How do you migrate eleven consumers without a risky big-bang cutover?","When two source systems disagree on stock, who wins, and how is that decided?","What's your phasing and cost curve — what gets delivered in quarter one vs later?"],
   stretch:"Add a contract-testing layer so a source system can't silently break the unified API."},

  {n:9,tier:"Brutal",archetypeKey:"unfixable",archetype:"Fix-the-unfixable-type",sector:"Logistics / Shipping",title:"The intermittent bug nobody can reproduce",
   summary:"A port-scheduling service occasionally double-books a berth — only sometimes, never in testing. Three engineers failed. A concurrency / race hunt: reproduce it, root-cause it, fix it, prove it. (Service provided separately.)",
   stack:["C#",".NET 8","async/await","optimistic concurrency","distributed lock","NBomber","xUnit","observability"],
   brief:"Woogle Freight has a port-scheduling service that occasionally assigns two ships to the same berth — but only sometimes, never in testing, always blamed on \"the network.\" Three engineers have failed to fix it. You're the last resort. A concurrency / race-condition hunt: the bug is real, intermittent, and lives in the gap between \"works on my machine\" and production load. A service that genuinely exhibits a race under concurrency is provided separately.",
   builds:["Reproduce an intermittent failure deterministically — the hardest part (load test, stress harness, forced interleaving).","Diagnose the actual root cause (a race / missing lock / non-atomic check-then-act), not a symptom.","Fix it correctly: proper concurrency control (optimistic concurrency, locking, or a queue) with reasoning for the choice.","Prove under concurrent load that it's gone.","Document the war story: how you caught something that \"only happens in production.\""],
   effort:"M–L and genuinely unpredictable — ~4–8 person-days. Honest DM answer: \"I can't promise a date on a heisenbug; I can promise a reproduction within X days, and a fix follows from that.\" Saying that out loud is a senior skill.",
   cost:"Low infra, high skill. One strong engineer. The value isn't hours — it's that intermittent production bugs cost companies enormously and almost nobody can fix them calmly.",
   accept:["A reproduction that triggers the bug on demand.","A correct concurrency fix with the reasoning written down.","Load test showing the double-booking can no longer happen.","A clear write-up of root cause and how it evaded everyone.","Repo + the stress test + the write-up."],
   questions:["How do you reproduce something that \"never happens in testing\"?","Optimistic vs pessimistic concurrency here — which did you choose and what did you trade away?","How do you give a delivery manager a timeline for a bug you haven't reproduced yet?"],
   stretch:"Make it distributed (two instances behind a load balancer) so an in-process lock is no longer enough and he has to reach for a real distributed solution."},

  {n:10,tier:"Brutal",archetypeKey:"capstone",archetype:"Capstone · build the thing itself",sector:"Pure tech play / Cross-sector",title:"Rebuild Sim for real — the resume-to-projects engine",
   summary:"Take the no-code Sim prototype and build the real engine: ingest a resume, understand stack and seniority, generate calibrated cross-sector briefs, persist the portfolio with the artifact gate enforced in code. The \"I took my wife's prototype to production\" capstone.",
   stack:["C#",".NET 8","Vertical Slice","CQRS / MediatR","document parsing","OpenAI API / Ollama","EF Core","SQL Server","JWT auth","Azure","CI/CD","Blazor","OpenTelemetry"],
   brief:"The capstone, and the one that ties everything together: take the no-code Sim prototype (built in Lovable) and build the real engine behind it. A service that ingests a resume, understands the candidate's stack and seniority, and generates calibrated, cross-sector project briefs — with the portfolio page as real, persisted output. The \"I took my wife's prototype and made it production\" story; it exercises nearly every skill on his resume plus the GenAI direction he's moving toward.",
   builds:["A real backend (.NET 8, clean architecture) that accepts a resume (PDF/docx), parses it, extracts stack + seniority + domains.","An LLM-backed generation step that produces briefs like these — structured, validated, calibrated to difficulty.","Persistence: users, projects, status, and the artifact links (repo/demo/write-up) behind each portfolio card.","The artifact gate enforced in code: a project can't reach the portfolio without its links.","Auth, deployed hosting, CI/CD — a real running product, not a demo."],
   effort:"XL — weeks, not days, and that's the point: it's a real product. Break it into phases and estimate each (parse → generate → persist → gate → deploy), which is itself the senior deliverable.",
   cost:"Real running costs: hosting + LLM tokens (or self-hosted Ollama). One strong full-stack engineer (him). Present a build plan with phased effort and a running-cost estimate — exactly how a principal pitches a new platform.",
   accept:["A resume goes in and real, calibrated, structured project briefs come out.","The portfolio page is real, persisted, and enforces the artifact gate in code.","It's deployed, authenticated, and a stranger can sign up and use it.","CI/CD pipeline is real — a push deploys.","Repo + live product + an architecture write-up and a phased build plan with estimates."],
   questions:["Walk us through your phasing and the effort estimate for each phase.","What's your running-cost model, and how would you keep LLM spend predictable?","How is the artifact gate enforced so it can't be bypassed — in the UI, or in the domain?","If this got real traction, what's the first thing that breaks and what's your scaling plan?"],
   stretch:"Make it multi-tenant so other people can upload their own resumes — the feature you mentioned wanting later, which turns a portfolio piece into a real product."},

  {n:11,tier:"Warm-up",archetypeKey:"build",archetype:"Build-type · greenfield",sector:"Travel / Hospitality",title:"Hotel room availability checker",
   summary:"A clean API that answers \"is a room of type X free between these dates,\" backed by a booking ledger so availability is always derived, never guessed.",
   stack:["C#",".NET 8","Minimal APIs","EF Core","SQL Server","xUnit","Swagger"],
   brief:"Voyagr (a 30-property boutique hotel group) wants a small service that answers one question reliably: is a room of a given type available between two dates? Today it's a spreadsheet and a lot of phone calls. Build the clean API the website and front desk can both call. Boring correctness over cleverness.",
   builds:["A .NET 8 API: check availability, hold a room, confirm a booking, cancel.","A bookings ledger so availability is computed, never stored as a fragile counter.","Date-range overlap logic that actually handles edge cases (same-day checkout/checkin).","Swagger docs and a few xUnit tests for the overlap rules."],
   effort:"S — about 2–3 person-days. The date-overlap logic is the only real thinking.",
   cost:"Near-zero infra. One developer. A clean warm-up to set the quality bar.",
   accept:["Overlapping-date edge cases handled correctly (proven by tests).","Availability always derived from the ledger.","Swagger works end to end.","README explains the booking model. Repo + demo."],
   questions:["How do you stop two people booking the last room at the same moment?","Same-day checkout and checkin on one room — available or not, and why?","Where does this break at 30 properties vs 3,000?"],
   stretch:"Add a short-lived \"hold\" that auto-expires so abandoned bookings free the room."},

  {n:12,tier:"Warm-up",archetypeKey:"build",archetype:"Build-type · integration",sector:"Agritech",title:"Sensor reading ingest for a smart farm",
   summary:"Ingest soil-moisture and temperature readings from field sensors, store them as a clean time series, and expose \"latest reading per sensor\" and \"last 24h\" queries.",
   stack:["C#",".NET 8","Web API","time-series storage","EF Core","Serilog","xUnit"],
   brief:"FarmFlow has hundreds of cheap field sensors pushing soil-moisture and temperature readings at intervals. Right now the data lands in a messy log file. Build a service that ingests the readings, stores them cleanly as a time series, and answers \"latest per sensor\" and \"last 24 hours for sensor X.\"",
   builds:["An ingest endpoint accepting batched sensor readings.","Clean time-series storage (a well-indexed table is fine for the demo).","Queries: latest-per-sensor, and a time-window range query.","Validation that rejects nonsense readings (e.g. impossible temperatures) and logs them."],
   effort:"S — about 2–3 person-days.",
   cost:"Low. One developer. The reusable asset is a clean ingest + query pattern.",
   accept:["Batched readings ingest correctly.","Latest-per-sensor and 24h-window queries return correct results.","Garbage readings are rejected and logged, not stored.","Repo + demo (Swagger or a tiny chart page)."],
   questions:["At a million readings a day, does your table design still answer queries fast?","How do you handle a sensor that goes silent — is \"no data\" different from \"zero\"?","What's the cheapest way to keep 2 years of history queryable?"],
   stretch:"Add a simple threshold alert (e.g. moisture below X) that flags a sensor."},

  {n:13,tier:"Core",archetypeKey:"build",archetype:"Build-type · workflow",sector:"Real estate / Proptech",title:"Property listing approval workflow",
   summary:"A multi-step approval pipeline — agent submits a listing, it goes through review and compliance checks, then publishes — with full state tracking and an audit trail of who did what.",
   stack:["C#",".NET 8","CQRS / MediatR","state machine","EF Core","SQL Server","Serilog","xUnit"],
   brief:"HomeNest lets agents submit property listings, but listings must pass a review and a compliance check before going live. Today it's email chaos and nobody knows a listing's status. Build a workflow service that moves a listing through clear states (submitted → in review → compliance → published / rejected), tracks who acted, and never lets a listing skip a step.",
   builds:["A state machine that enforces legal transitions (no skipping review).","Endpoints for each action (submit, approve, reject, request changes, publish).","An audit trail: who moved it, when, with what note.","CQRS split so commands (state changes) and queries (status views) are clean."],
   effort:"M — about 5–6 person-days. The state machine and its guarded transitions are the meat.",
   cost:"Moderate. One senior dev. The transferable asset is the workflow engine pattern — reusable across any approval process.",
   accept:["Illegal transitions are rejected (you can't publish an unreviewed listing).","Every transition is audited with actor and timestamp.","Current status of any listing is one query.","README documents the state diagram. Repo + demo."],
   questions:["How do you make sure a listing can never skip compliance, even via a direct API call?","If the rules change next quarter, how much of your code changes?","How would you show an agent exactly why their listing was rejected?"],
   stretch:"Make the workflow definition data-driven so a new step can be added without code."},

  {n:14,tier:"Core",archetypeKey:"polish",archetype:"Snapple-type · polish",sector:"Edtech",title:"Quiz-grading API built to a craft standard",
   summary:"A simple quiz-grading service where the functionality is easy but the bar is craft — clean contract, consistent errors, partial-credit edge cases handled gracefully, docs a teacher's dev team could integrate in minutes.",
   stack:["C#",".NET 8","Minimal APIs","ProblemDetails","API versioning","OpenAPI","xUnit","Serilog"],
   brief:"Learnly is building quizzes and wants a grading API that just feels solid. Submitting answers and getting a score is trivial; the bar is craft — every edge case (blank answers, partial credit, multi-select, out-of-range) handled cleanly and documented, errors consistent, docs flawless.",
   builds:["A clean, versioned grading API covering several question types.","Careful handling of partial credit, blanks, and malformed submissions.","Consistent error shape everywhere; great OpenAPI docs.","A test suite that's almost a spec — every grading rule has a test."],
   effort:"M — about 4–5 person-days. The grading is quick; covering every edge case correctly is the work.",
   cost:"Low infra. One dev who sweats detail. The \"cost\" is thoroughness.",
   accept:["Every question type and edge case graded correctly, proven by tests.","Consistent documented error format.","A stranger can integrate from the README alone.","Repo + live demo + OpenAPI page."],
   questions:["How do you grade a multi-select where the student is half right?","What happens on a malformed submission, and is that behaviour documented?","Where's the line between thoroughness and over-engineering here?"],
   stretch:"Add a \"regrade\" endpoint that re-scores submissions if a question's correct answer is fixed after the fact."},

  {n:15,tier:"Core",archetypeKey:"debug",archetype:"Debug-type · inherited code",sector:"Telecom",title:"The billing rounding bug eating revenue",
   summary:"A telecom usage-billing service is losing fractions of a cent per call in a way that adds up to real money. Handed the code: find the rounding/accumulation flaw, prove it, fix it without breaking correct bills. (Broken codebase provided separately.)",
   stack:["C#",".NET 8","xUnit","decimal precision","debugging","Git"],
   brief:"TeleWave bills customers for call usage. Finance noticed the monthly totals are very slightly off — fractions of a cent per call, but across millions of calls it's real money, and sometimes in the customer's favour, sometimes the company's. You're handed the billing code: find the flaw, prove it with a failing test, fix it minimally. A broken codebase is provided separately.",
   builds:["Read an unfamiliar billing codebase with a planted precision/accumulation bug.","Reproduce the discrepancy with a failing test.","Fix it minimally (likely decimal handling / rounding order / accumulation).","Regression tests so it can't silently return.","A root-cause note on why money math needs special care."],
   effort:"S–M — about 2–4 person-days, unpredictable. \"A day to find, a day to prove and fix.\"",
   cost:"Pure engineering time. One developer. Demonstrates calm in someone else's money code.",
   accept:["Failing-then-passing test pinpointing the bug.","Correct bills still correct (no regressions).","Minimal, explained fix.","Root-cause write-up. Repo with before/after commits."],
   questions:["Why does rounding order matter when you sum millions of small charges?","How would you audit historical bills for the same error?","How do you prevent this whole class of bug going forward?"],
   stretch:"Add a property-based test that throws thousands of random usage patterns at the calculator."},

  {n:16,tier:"Hard",archetypeKey:"rescue",archetype:"Rescue-type · turnaround",sector:"Nonprofit / NGO",title:"Stalled donor management system, shipped on a shoestring",
   summary:"A donor-management rebuild has been stuck for months with no budget. Come in, cut to the core (record donations, track donors, produce receipts), and ship something a small charity can actually use this month.",
   stack:["C#",".NET 8","Blazor","EF Core","QuestPDF","Azure free tier","GitHub Actions"],
   brief:"HopeWorks, a small charity, has been trying to replace its donor spreadsheet for months. No budget, volunteer devs came and went, nothing shipped. You're brought in to rescue it on a shoestring: record donations, track donors, generate tax receipts. Ruthlessly cut everything else.",
   builds:["A scope-cut memo: the three things that matter, everything else deferred.","Record donations against donors; basic donor list and history.","Generate a proper tax-receipt PDF.","Deployed on free/cheap hosting, genuinely usable by non-technical staff."],
   effort:"M–L — about 6–8 person-days, but scope discipline is the headline skill.",
   cost:"Deliberately near-zero. One developer. Maximum usefulness per zero budget — a strong story about pragmatism.",
   accept:["The scope-cut memo exists and is defensible.","Donations record and receipts generate correctly.","Deployed and usable by a non-technical volunteer.","Deferred work named. Repo + live demo + memo."],
   questions:["With zero budget, how did you decide the three things to build?","How do you hand this to volunteers who aren't developers?","What would you build next if a grant came in, and what would you still refuse?"],
   stretch:"Add a simple year-end summary export the charity can hand to its accountant."},

  {n:17,tier:"Hard",archetypeKey:"ai",archetype:"AI-agent-type · build",sector:"Legal / Compliance",title:"Contract-clause review agent",
   summary:"An agent that reads a contract, extracts key clauses, flags risky or missing terms against a checklist, and escalates anything ambiguous to a human lawyer — with structured, validated output, never free text the business can't trust.",
   stack:["C#",".NET 8","OpenAI API / Ollama","structured output","JSON schema validation","RAG basics","Serilog","xUnit"],
   brief:"LexGuard wants an agent that reviews incoming contracts: pull out key clauses (term, liability, termination, payment), check them against a required-clause checklist, flag what's risky or missing, and escalate genuinely ambiguous calls to a human lawyer. The hard part is reliability and knowing when NOT to decide.",
   builds:["A pipeline: ingest contract text → extract clauses → check against checklist → flag/escalate.","LLM integration with strictly structured, schema-validated output.","A confidence rule: low-confidence or missing clauses escalate, never auto-approve.","Guardrails against hallucinated clauses (cite the source span)."],
   effort:"L — about 8–10 person-days. Extraction is easy; trustworthiness and citing sources are hard.",
   cost:"Variable LLM cost (discuss OpenAI vs Ollama). One AI-fluent dev. Note: this is decision-support, not legal advice — a boundary worth stating.",
   accept:["Structured, validated output every time, or a loud failure.","Flagged clauses cite where in the contract they came from.","Ambiguous/missing clauses escalate to a human.","README explains pipeline, escalation, cost model. Repo + demo."],
   questions:["How do you stop the agent inventing a clause that isn't there?","What's the liability line — where must a human always decide?","Cost at 10,000 contracts a month, and how to cut it?"],
   stretch:"Add a small eval set of contracts with known answers to measure extraction accuracy."},

  {n:18,tier:"Hard",archetypeKey:"build",archetype:"Build-type · real-time",sector:"Gaming",title:"Real-time leaderboard service",
   summary:"A leaderboard backend that ingests a flood of score updates and serves top-N and \"my rank\" instantly, staying correct and fast under bursty load — the kind of thing that quietly melts under a launch spike.",
   stack:["C#",".NET 8","SignalR","Redis (sorted sets)","background processing","load testing","xUnit"],
   brief:"PixelForge is launching a mobile game and needs a leaderboard that survives launch day: thousands of score updates a second, instant top-100, and \"where do I rank\" for any player. It has to stay correct and fast when traffic spikes — the classic thing that works in dev and dies at launch.",
   builds:["A score-ingest endpoint that handles bursts without losing updates.","Fast top-N and per-player rank queries (Redis sorted sets are the natural tool).","Real-time push of rank changes (SignalR) for a live feel.","A load test that simulates a launch spike and proves it holds."],
   effort:"L — about 7–9 person-days. Correctness under concurrency and the load test are the real work.",
   cost:"Moderate (a Redis instance). One strong dev. The value is surviving the spike that kills naive implementations.",
   accept:["Top-N and my-rank are correct and fast under load.","No score updates lost during a simulated burst.","Load test demonstrates the spike is handled.","README explains the data structure choice. Repo + demo."],
   questions:["Why Redis sorted sets over a SQL ORDER BY here?","What happens to in-flight updates if the service restarts mid-spike?","How do you keep \"my rank\" accurate for 10 million players?"],
   stretch:"Add seasonal leaderboards that reset, without downtime during the rollover."},

  {n:19,tier:"Hard",archetypeKey:"build",archetype:"Build-type · event-driven",sector:"Automotive / IoT",title:"Connected-vehicle event pipeline",
   summary:"An event-driven pipeline that ingests telemetry from connected vehicles (location, diagnostics, alerts), processes it asynchronously through a queue, and exposes fleet health — built to absorb spikes without dropping events.",
   stack:["C#",".NET 8","message queue (Service Bus / RabbitMQ)","background workers","EF Core","OpenTelemetry","xUnit"],
   brief:"DriveLink runs a fleet of connected vehicles streaming telemetry — GPS, engine diagnostics, fault alerts. They need a pipeline that ingests this reliably, processes it asynchronously (so a spike doesn't drop data), and surfaces fleet health and active faults. Decouple ingest from processing with a queue.",
   builds:["An ingest endpoint that publishes events to a queue (never processes inline).","Background workers that consume, process, and store events.","Fleet-health and active-fault queries.","Handling for poison messages and retries; tracing across the pipeline."],
   effort:"L — about 7–9 person-days. The async decoupling and failure handling are the senior bits.",
   cost:"Moderate (a message broker). One strong dev. Asset: a resilient ingest pattern reusable across any high-volume telemetry.",
   accept:["A spike of events is absorbed by the queue, none dropped.","A poison message doesn't block the pipeline.","Fleet health and faults queryable. Tracing shows an event's journey.","README explains the architecture. Repo + demo."],
   questions:["Why decouple ingest from processing with a queue here?","What happens to a message your worker can't process — and how many times do you retry?","How do you not lose data if a worker crashes mid-processing?"],
   stretch:"Add idempotent processing so a redelivered message can't double-count a fault."},

  {n:20,tier:"Brutal",archetypeKey:"architect",archetype:"Architect-type · consolidation",sector:"Govtech / Public sector",title:"Unify a city's fragmented citizen-services APIs",
   summary:"A city has a dozen siloed services (permits, tax, complaints, licences) each with its own API, auth, and data model. Design and prove a unified citizen-services layer with a single identity and per-service tracking. His CSAPI win at civic scale.",
   stack:["C#",".NET 8","Vertical Slice","CQRS / MediatR","API gateway","OAuth / identity","OpenTelemetry","ADRs","C4 diagrams"],
   brief:"Metro City has a dozen citizen-facing services — permits, property tax, complaints, business licences — each built separately with its own API, login, and data shape. Citizens juggle a dozen logins and nothing talks. You're the architect to design and prove a unified citizen-services layer: one identity, one consistent contract, per-service usage tracking. His CSAPI consolidation, at civic scale.",
   builds:["An ADR + diagrams: the fragmented current state vs unified target.","A reference unified API fronting 2–3 modelled services with one consistent contract.","A single citizen identity across services (federated/OAuth).","Per-service usage tracking and a phased migration plan."],
   effort:"L — months in reality; ~9–11 person-days for a convincing ADR, identity model, and reference slice. The thinking is the deliverable.",
   cost:"Public-sector context: a team over multiple quarters, plus identity infra and procurement realities. Present as a phased programme with a cost curve and risk register.",
   accept:["An ADR an architecture board would accept.","Reference API unifying 2–3 services under one contract and one identity.","Per-service usage tracked. Phased, no-big-bang migration plan.","Repo + diagrams + demo."],
   questions:["How do you give citizens one login across services that were never designed to share identity?","When two departments' data disagrees about a citizen, who's right?","What's the phasing and risk register for a public-sector rollout?"],
   stretch:"Add an accessibility and audit layer, since public services carry legal obligations most private ones don't."},

  {n:21,tier:"Brutal",archetypeKey:"unfixable",archetype:"Fix-the-unfixable-type",sector:"Fintech / Payments",title:"The deadlock that only happens at month-end",
   summary:"A payments reconciliation job intermittently hangs — but only under month-end load, never reproducibly. A database-deadlock / lock-ordering hunt: reproduce it deterministically, root-cause it, fix it, prove it. (Service provided separately.)",
   stack:["C#",".NET 8","SQL Server","transactions & isolation levels","deadlock graphs","load testing","xUnit"],
   brief:"PayNova's reconciliation job hangs occasionally — only at month-end when volume peaks, never in testing. Ops just \"restart it.\" Two engineers have given up. You're the last resort. This is a database-deadlock / lock-ordering hunt living in concurrent transactions under load. A service that genuinely deadlocks under concurrency is provided separately.",
   builds:["Reproduce the deadlock deterministically (concurrent load harness, forced interleaving).","Read the deadlock graph; identify the lock-ordering / isolation-level root cause.","Fix correctly (consistent lock ordering, isolation tuning, or restructuring the transaction) with reasoning.","Prove under concurrent load it no longer deadlocks.","Write the war story."],
   effort:"M–L, genuinely unpredictable — ~5–9 person-days. \"I can promise a reproduction in X days; the fix follows from understanding it.\"",
   cost:"Low infra, high skill. One strong engineer. Month-end hangs cost real money and almost nobody fixes them calmly.",
   accept:["On-demand reproduction of the deadlock.","Correct fix with written reasoning about lock ordering / isolation.","Load test proving it's gone.","Root-cause write-up. Repo + stress test + write-up."],
   questions:["How do you reproduce a deadlock that only shows up at peak volume?","What isolation level were you on, and how did that contribute?","How do you give finance a fix date for a bug you haven't reproduced yet?"],
   stretch:"Add deadlock detection + automatic safe retry so even an unforeseen future deadlock degrades gracefully."},

  {n:22,tier:"Warm-up",archetypeKey:"build",archetype:"Build-type · greenfield",sector:"Food delivery",title:"Delivery ETA calculator service",
   summary:"A small service that estimates delivery time from prep time, distance, and current order load — clean, testable, and honest about its assumptions.",
   stack:["C#",".NET 8","Minimal APIs","EF Core","xUnit","Swagger"],
   brief:"QuickBite wants a clean little service to estimate delivery ETAs from prep time, distance, and how busy the kitchen is right now. Today it's a flat \"45 minutes\" for everything and customers are annoyed. Build the honest version.",
   builds:["An endpoint that returns an ETA given order details and current load.","A transparent, documented formula (no magic numbers).","Tests covering quiet vs slammed-kitchen scenarios.","Swagger docs."],
   effort:"S — about 2 person-days.",
   cost:"Near-zero. One developer.",
   accept:["ETA changes sensibly with load and distance.","The formula is documented, not hidden.","Tests cover the extremes. Repo + demo."],
   questions:["How do you keep the ETA honest rather than optimistic to win the order?","What data would make this materially better, and is it worth collecting?","How would you measure whether your ETAs are actually accurate?"],
   stretch:"Feed back actual delivery times to self-correct the estimate over time."},

  {n:23,tier:"Core",archetypeKey:"build",archetype:"Build-type · integration",sector:"HR / Recruitment tech",title:"Multi-source candidate de-duplication service",
   summary:"Candidates arrive from job boards, referrals, and the careers page — often the same person twice. Build a service that ingests from multiple sources and intelligently merges duplicates into one canonical record.",
   stack:["C#",".NET 8","Web API","fuzzy matching","EF Core","SQL Server","Serilog","xUnit"],
   brief:"HirePath pulls candidates from three job boards, employee referrals, and its own careers page. The same person often appears multiple times with slightly different details. Build a service that ingests all sources and merges likely-duplicate candidates into one canonical profile — without wrongly merging two different people.",
   builds:["Ingest from multiple differently-shaped sources (echoes his integration work).","A matching strategy (email exact-match plus fuzzy name/phone) with a confidence score.","Auto-merge high-confidence; flag medium-confidence for human review; never merge low-confidence.","An audit of every merge so it can be undone."],
   effort:"M — about 5–6 person-days. The matching thresholds and the \"don't wrongly merge\" safety are the hard part.",
   cost:"Moderate. One senior dev. The asset is a reusable identity-resolution pattern.",
   accept:["Clear duplicates merge; clear non-duplicates don't.","Borderline cases are flagged, not auto-merged.","Every merge is auditable and reversible.","README explains the matching logic. Repo + demo."],
   questions:["What's worse — merging two different people, or missing a duplicate? How does that shape your thresholds?","How do you undo a bad merge cleanly?","How would you tune confidence without a labelled dataset?"],
   stretch:"Add a feedback loop where human review decisions improve the matching over time."},

  {n:24,tier:"Core",archetypeKey:"build",archetype:"Build-type · security",sector:"Cybersecurity / SaaS",title:"API key management service done right",
   summary:"A service for issuing, scoping, rotating, and revoking API keys — with keys hashed at rest, scoped permissions, and immediate revocation. Security fundamentals most teams get subtly wrong.",
   stack:["C#",".NET 8","Web API","secret hashing","scoped claims","rate limiting","SQL Server","xUnit"],
   brief:"SentinelSaaS needs to let customers create API keys for their integrations: issue a key, scope it to certain permissions, rotate it, revoke it instantly. The catch is doing it securely — keys hashed at rest, never logged, revocation that takes effect immediately. Build the version a security reviewer would approve.",
   builds:["Issue keys with scoped permissions; show the raw key once, store only a hash.","Validate incoming keys against the hash; enforce scopes per request.","Rotation (issue new, grace-expire old) and instant revocation.","Keys never appear in logs or error messages."],
   effort:"M — about 5–6 person-days. Getting the security details exactly right is the work.",
   cost:"Low infra. One senior dev plus a security review. The value is fundamentals done correctly.",
   accept:["Raw keys shown once, only hashes stored.","Revocation is immediate; scopes enforced.","No key material in any log or error.","README explains the security model. Repo + demo."],
   questions:["Why hash API keys rather than encrypt them?","How do you make revocation instant without checking the database on every single request?","What's your rotation story so customers aren't broken by it?"],
   stretch:"Add per-key usage analytics (echoing his per-consumer tracking from CSAPI)."},

  {n:25,tier:"Hard",archetypeKey:"build",archetype:"Build-type · data migration",sector:"Banking (legacy modernisation)",title:"Zero-downtime migration off a legacy schema",
   summary:"Migrate a banking module from an old, gnarly database schema to a clean new one — with the system staying live the whole time. The expand-migrate-contract pattern, which is where most real modernisation lives.",
   stack:["C#",".NET 8","EF Core","SQL Server","dual-write pattern","feature flags","background backfill","xUnit"],
   brief:"OldGuard Bank needs to move an accounts module from a 15-year-old schema to a clean new design — but the system can't go down, and data can't be lost or corrupted for a second. Implement the expand/migrate/contract approach: dual-write, backfill, verify, cut over, clean up. This is the real shape of legacy modernisation.",
   builds:["A new schema alongside the old (expand).","Dual-write so both stay in sync during transition.","A background backfill of historical data, with verification.","A feature-flagged cutover to reads from the new schema, then retire the old.","A rollback plan if verification fails."],
   effort:"L — about 8–10 person-days. The dual-write correctness and verification are unforgiving.",
   cost:"Moderate. One strong dev. The skill — migrating live financial data without downtime — is rare and highly valued.",
   accept:["Dual-write keeps old and new in sync, proven.","Backfill completes and verifies against the source.","Cutover is flag-controlled and reversible.","README documents the phases and rollback. Repo + demo (simulated)."],
   questions:["How do you guarantee no data is lost during dual-write?","How do you verify the new schema matches the old before cutover?","If verification fails at 2am, what's your rollback?"],
   stretch:"Add a reconciliation report that proves, row by row, the migration was lossless."},

  {n:26,tier:"Hard",archetypeKey:"polish",archetype:"Snapple-type · polish",sector:"Developer tools",title:"A CLI tool developers actually enjoy using",
   summary:"A command-line tool (e.g. a project scaffolder or log analyser) built to the standard of the tools developers love — fast, great help text, sensible defaults, clear errors, installable in one command. Polish as the whole point, in a different medium.",
   stack:["C#",".NET 8","System.CommandLine","NuGet packaging","dotnet tool","xUnit","great docs"],
   brief:"ToolForge wants an internal CLI that engineers reach for daily — say a project scaffolder or a log analyser. The functionality is modest; the bar is that it feels as good as the best CLIs: instant, discoverable help, sensible defaults, clear errors, installable in one command. Craft in a non-API medium.",
   builds:["A .NET CLI with well-structured commands and excellent --help.","Sensible defaults; clear, actionable error messages.","Packaged as a dotnet global tool, installable in one line.","Genuinely good README with examples."],
   effort:"M–L — about 6–7 person-days. The features are quick; the experience polish is the work.",
   cost:"Low. One dev who cares about DX. The \"cost\" is taste.",
   accept:["Installs in one command and runs.","Help text lets a stranger use it without docs.","Errors are clear and tell you how to fix the problem.","Repo + the published tool + README."],
   questions:["What makes a CLI feel good versus tolerable?","How do you choose defaults so most users never need flags?","Where would more polish stop being worth the time?"],
   stretch:"Add shell autocompletion so the tool feels first-class in the terminal."},

  {n:27,tier:"Hard",archetypeKey:"build",archetype:"Build-type · observability",sector:"E-commerce",title:"Make a black-box checkout observable",
   summary:"An e-commerce checkout fails sometimes and nobody knows why — no logs, no metrics, no traces. Retrofit observability so the team can finally see what's happening, then use it to find a real problem. The unglamorous skill that separates seniors.",
   stack:["C#",".NET 8","OpenTelemetry","Serilog","metrics","distributed tracing","dashboards"],
   brief:"ShopSphere's checkout drops a small percentage of orders and the team is flying blind — minimal logging, no metrics, no tracing. Retrofit proper observability into the existing flow (logs, metrics, traces), then use what you built to actually locate a planted failure. Seeing the problem is most of solving it.",
   builds:["Structured logging with correlation IDs across the checkout steps.","Metrics (success rate, latency per step, error counts).","Distributed tracing so one order's journey is visible end to end.","A dashboard, and a written diagnosis of the failure he found using it."],
   effort:"L — about 7–8 person-days. Instrumenting cleanly without rewriting the app is the skill.",
   cost:"Moderate (observability backend, many free tiers exist). One senior dev. The payoff: a previously invisible system becomes debuggable forever.",
   accept:["Logs, metrics, and traces are in place and correlated.","One order's full journey is traceable.","The planted failure is found and diagnosed using the new telemetry.","README shows before/after visibility. Repo + demo (dashboard screenshots ok)."],
   questions:["What's the difference between logs, metrics, and traces, and when does each help?","How do you instrument without drowning in noise or cost?","How would you alert on this failure before a customer reports it?"],
   stretch:"Add an SLO and an alert that fires when checkout success drops below it."},

  {n:28,tier:"Brutal",archetypeKey:"architect",archetype:"Architect-type · scale",sector:"Social / High-traffic SaaS",title:"Design a feed that survives 10x growth",
   summary:"Design and prototype a social activity feed that works at small scale and has a credible architecture for 10x growth — caching, fan-out strategy, pagination, the read/write trade-offs. The classic systems-design interview, built for real.",
   stack:["C#",".NET 8","Redis","caching strategies","fan-out-on-write vs read","pagination","OpenTelemetry","ADRs"],
   brief:"ConnectHub's activity feed works now but will fall over as it grows. Design (ADR + diagrams) and prototype a feed with a credible scaling story: how posts fan out to followers, how you cache, how you paginate, and the trade-offs between computing the feed on write vs on read. Build a working slice and document the path to 10x.",
   builds:["An ADR weighing fan-out-on-write vs fan-out-on-read, with the trade-offs.","A working feed slice (post, follow, get feed) with caching.","Cursor-based pagination that stays correct as new posts arrive.","A written scaling plan: what changes at 10x, what it costs."],
   effort:"L — ~8–10 person-days for ADR, diagrams, and a convincing slice. The reasoning is the deliverable.",
   cost:"Moderate now; the point is projecting cost at scale. One strong dev. This is the canonical senior systems-design skill made concrete.",
   accept:["An ADR that defends the fan-out choice with trade-offs.","A working feed slice with caching and correct pagination.","A scaling plan to 10x with a cost projection.","Repo + diagrams + demo."],
   questions:["Fan-out on write or on read — which did you choose and for whom does it break?","How does a celebrity with 10 million followers change your design?","Where's your first bottleneck at 10x, and what does fixing it cost?"],
   stretch:"Handle the \"celebrity problem\" with a hybrid fan-out and explain when it kicks in."},

  {n:29,tier:"Brutal",archetypeKey:"rescue",archetype:"Rescue-type · turnaround",sector:"Healthtech",title:"Rescue a failing appointment-booking platform under live load",
   summary:"A clinic-booking platform is in production, falling over daily, double-booking patients, and the vendor walked. Come in mid-crisis, stabilise it without a rewrite, fix the worst failures, and chart a path out — all while it stays live.",
   stack:["C#",".NET 8","SQL Server","concurrency control","observability","feature flags","incremental refactoring"],
   brief:"MediBook is live, used by real clinics daily, and breaking — double-bookings, slow pages, occasional data loss. The original vendor is gone. You can't take it down and you can't rewrite it. Stabilise it in place: triage the worst failures, fix them incrementally, add enough visibility to stop flying blind, and lay out a realistic recovery roadmap. This is rescue plus turnaround under live fire — the hardest real scenario.",
   builds:["A triage doc: the failures ranked by patient impact.","The concurrency fix for double-booking (ties to his race-condition skills).","Enough observability to see failures as they happen.","Incremental, flag-guarded fixes — no big-bang rewrite.","A recovery roadmap: stabilise → improve → modernise."],
   effort:"L — ~9–11 person-days for a convincing stabilisation slice + roadmap. Judgement under constraint is the headline.",
   cost:"Constrained and high-pressure. One senior firefighter. The story — calm competence in a live crisis — is exactly what principal roles screen for.",
   accept:["A prioritised triage of failures by impact.","The double-booking concurrency bug fixed and proven.","Observability added so failures are visible.","A phased recovery roadmap. Repo + demo + the docs."],
   questions:["It's live and breaking — what do you fix first, and why patient-impact over everything?","How do you change a system you can't take down and don't fully understand?","When do you stop firefighting and start the real fix?"],
   stretch:"Add a safety net (graceful degradation) so the worst failure becomes an inconvenience, not data loss."},

  {n:30,tier:"Brutal",archetypeKey:"architect",archetype:"Architect-type · greenfield platform",sector:"Cross-sector / Pure tech play",title:"Design a multi-tenant SaaS platform from scratch",
   summary:"Architect a multi-tenant SaaS foundation — tenant isolation, per-tenant data, auth, onboarding, and a billing hook — the reusable backbone under any B2B product. The capstone for platform-level architecture thinking.",
   stack:["C#",".NET 8","Vertical Slice","multi-tenancy","OAuth / identity","EF Core","Azure","CI/CD","ADRs","C4 diagrams"],
   brief:"Build the architecture and a working core for a multi-tenant SaaS platform that any B2B product could sit on: how tenants are isolated, how data is partitioned (shared schema vs schema-per-tenant vs database-per-tenant — and why), authentication, tenant onboarding, and a hook for per-tenant billing. This is platform thinking — the foundation, not a feature.",
   builds:["An ADR choosing and defending a tenant-isolation strategy with trade-offs.","A working core: create a tenant, isolate its data, authenticate its users.","Tenant onboarding flow and a per-tenant billing/usage hook.","Diagrams and a written path from MVP to production."],
   effort:"L–XL — ~10–12 person-days for ADR, core, and diagrams. Genuinely architect-level.",
   cost:"Present as a phased platform investment with a cost model — exactly how a principal pitches foundational work that doesn't ship a visible feature on day one.",
   accept:["An ADR defending the isolation strategy with real trade-offs.","A working core that isolates two tenants' data provably.","Onboarding + a billing/usage hook.","Diagrams + MVP-to-production path. Repo + demo."],
   questions:["Shared schema, schema-per-tenant, or database-per-tenant — which, and what did you trade?","How do you guarantee one tenant can never see another's data?","How do you justify spending on a platform that ships no visible feature this quarter?"],
   stretch:"Add a noisy-neighbour safeguard so one heavy tenant can't degrade everyone else."}
];
